# number of training samples to use for encoding and decoding each time for the LSTM
LSTM_WINDOW_SIZE: 15

# encoding dimension for LSTM autoencoder
LSTM_ENCODING_DIMENSION: 10

# determine threshold for classification from this percent of training set that had lower errors
# (e.g get the threshold error in which 99% of training set had lower values than)
LSTM_THRESHOLD_FROM_TRAINING_PERCENT:  0.99
LSTM_THRESHOLD_FROM_TRAINING_PERCENT_SINGLE: 1.0

#these flight have corrupted data - "speed" attribute
EXCLUDE_FLIGHTS:
  "washington_to_san_francisco":
    - "38.csv"
    - "41.csv"
