ANOMALY_DETECTION_METHODS = 'anomaly_detection_methods'
FEATURE_SELECTION_METHODS = 'feature_selection_methods'
SIMILARITY_FUNCTIONS = 'similarity_functions'
LSTM_ACTIVATION = 'lstm_activation'
LSTM_LOSS = 'lstm_loss'
LSTM_OPTIMIZER = 'lstm_optimizer'
LSTM_WINDOW = 'lstm_window'
LSTM_ENCODER_DIMENSION= 'lstm_encoder_dimension'
LSTM_THRESHOLD_FROM_TRAINING_PERCENT = "lstm_threshold_from_training_percent"